/**
 * Use Case Generator — Generates use case skeleton.
 */

export function generateUseCase(name: string, module: string): string {
  const commandName = `${name}Command`;
  const handlerName = `${name}Handler`;
  const pascalModule = module.charAt(0).toUpperCase() + module.slice(1);

  return `/**
 * ${name} — Use case for ${pascalModule} domain.
 *
 * Generated by eos-cli. Implement use case logic below.
 */

import { CommandBase } from '../../../kernel/application/command/command';
import { ICommandHandler } from '../../../kernel/application/command/command-handler';
import { Result } from '../../../shared/result/result';

export class ${commandName} extends CommandBase {
  // TODO: Add command properties
  constructor() {
    super();
  }
}

export class ${handlerName} implements ICommandHandler<${commandName}, void> {
  async execute(command: ${commandName}): Promise<Result<void>> {
    // TODO: Implement use case logic
    return Result.ok(undefined);
  }
}
`;
}
