/**
 * Value Object Generator — Generates value object skeleton.
 */

export function generateValueObject(name: string, module: string): string {
  const pascalModule = module.charAt(0).toUpperCase() + module.slice(1);

  return `/**
 * ${name} — Value object for ${pascalModule} domain.
 *
 * Generated by eos-cli. Implement value logic below.
 */

import { ValueObject } from '../../../shared/entity/value-object';

export class ${name} extends ValueObject<{ value: string }> {
  get value(): string {
    return this._value.value;
  }

  static create(value: string): ${name} {
    // TODO: Add validation
    return new ${name}({ value });
  }

  toString(): string {
    return this._value.value;
  }
}
`;
}
