/**
 * Aggregate Generator — Generates aggregate skeleton.
 */

export function generateAggregate(name: string, module: string): string {
  const className = `${name}Aggregate`;
  const idClassName = `${name}Id`;
  const pascalModule = module.charAt(0).toUpperCase() + module.slice(1);

  return `/**
 * ${className} — ${pascalModule} aggregate root.
 *
 * Generated by eos-cli. Implement business rules below.
 */

import { AggregateRoot } from '../../../shared/entity/aggregate-root';
import { NumberId } from '../../../shared/entity/identifier';

export class ${idClassName} extends NumberId {
  static create(value: number): ${idClassName} {
    return new ${idClassName}({ value });
  }
}

export class ${className} extends AggregateRoot {
  private _status: string;

  constructor(id: number) {
    super(id);
    this._status = 'active';
  }

  get status(): string {
    return this._status;
  }

  /**
   * Validate aggregate invariants.
   * TODO: Implement business invariants.
   */
  validateInvariants(): void {
    // TODO: Add invariant checks
  }
}
`;
}
