/**
 * Event Generator — Generates domain event skeleton.
 */

export function generateEvent(name: string, module: string): string {
  const className = `${name}Event`;
  const pascalModule = module.charAt(0).toUpperCase() + module.slice(1);

  return `/**
 * ${className} — Domain event for ${pascalModule} domain.
 *
 * Generated by eos-cli. Implement event data below.
 */

import { DomainEventBase } from '../../../shared/domain-event/domain-event';

export class ${className} extends DomainEventBase {
  public readonly eventType = '${module}.${name.toLowerCase()}';

  constructor(
    eventId: string,
    // TODO: Add event properties
  ) {
    super(eventId);
  }
}
`;
}
