/**
 * Entity Generator — Generates entity skeleton.
 */

export function generateEntity(name: string, module: string): string {
  const pascalModule = module.charAt(0).toUpperCase() + module.slice(1);

  return `/**
 * ${name} — Entity for ${pascalModule} domain.
 *
 * Generated by eos-cli. Implement entity logic below.
 */

import { BaseEntity } from '../../../shared/entity/entity.base';

export class ${name} extends BaseEntity {
  // TODO: Add entity properties and business methods
}
`;
}
