/**
 * Repository Generator — Generates repository skeleton.
 */

export function generateRepository(name: string, module: string): string {
  const className = `${name}Repository`;
  const aggregateName = `${name}Aggregate`;
  const pascalModule = module.charAt(0).toUpperCase() + module.slice(1);

  return `/**
 * ${className} — Repository for ${pascalModule} aggregate.
 *
 * Generated by eos-cli. Implement persistence logic below.
 */

import { IPersistenceAdapter } from '../../../kernel/infrastructure/persistence-adapter';
import { IMapper } from '../../../kernel/infrastructure/mapper-base';
import { RepositoryBase } from '../../../kernel/infrastructure/repository-base';

export class ${className} extends RepositoryBase<any, any, number> {
  constructor(
    adapter: IPersistenceAdapter<any, any, number>,
    mapper: IMapper<any, any>,
  ) {
    super(adapter, mapper);
  }

  // TODO: Add domain-specific query methods
}
`;
}
