export enum LessonStatus {
  DRAFT = 'DRAFT',
  SCHEDULED = 'SCHEDULED',
  TEACHING = 'TEACHING',
  FINISHED = 'FINISHED',
  ARCHIVED = 'ARCHIVED',
  CANCELLED = 'CANCELLED',
  SUSPENDED = 'SUSPENDED',
  RESCHEDULED = 'RESCHEDULED',
  MAKEUP_PENDING = 'MAKEUP_PENDING',
  MAKEUP_COMPLETED = 'MAKEUP_COMPLETED',
}
