export enum ReminderType {
  CLASS_REMINDER = 'CLASS_REMINDER',
  ATTENDANCE_REMINDER = 'ATTENDANCE_REMINDER',
  CONTRACT_EXPIRY = 'CONTRACT_EXPIRY',
  MISSION_STALL = 'MISSION_STALL',
  SYSTEM = 'SYSTEM',
}
